# Change these first
owner: giocoliere # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Wesbsite v0.7
    url: https://www.giocoliere.dev
  - name: Wesbsite v0.1
    url: https://gioco.is-a.dev
  - name: Giocoliere | Links
    url: https://links.gioco.lol
  - name: Giocoliere | Blog
    url: https://blog.gioco.lol
 - name: Giocoliere - Test Statuspage 
    url: https://test.gioco.lol
  - name: Humanaelitterae
    url: https://humanaelitterae.com
  - name: Modmail
    url: https://modmail.creeperhub.net
  - name: CreeperHUB
    url: https://creeperhub.net
  - name: creepers.sbs
    url: https://creepers.sbs
  - name: Creepercraft
    url: https://creepercraft.net
  - name: Otakuforge
    url: https://creeperhub.net/otakuforge
  - name: CreeperLAB
    url: https://creeperlab.org

    

status-website:
  favicon: https://giocoliere.dev/assets/img/logo.png
  metaTags:
    - name: "description"
      content: "Status page of Giocoliere"
    - name: "og:description"
      content: "Status page of Giocoliere"
    - name: "twitter:description"
      content: "Status page of Giocoliere"
    - name: "keywords"
      content: "Giocoliere, Giocolieredev, Dev, CreeperHUB, Developer, Creepercraft, CreeperLAB, Programming, Gaming, Minecraft, Development, HumanaeLitterae"
    - name: "author"
      content: "Giocoliere"
    - name: "og:title"
      content: "Giocoliere | Status"
    - name: "twitter:title"
      content: "Giocoliere | Status"
    - name: "robots"
      content: "follow, index"
    - name: "theme-color"
      content: "#69a6ce"
    - name: "og:image"
      content: "https://giocoliere.dev/assets/img/preview.png"
    - name: "twitter:image"
      content: "https://giocoliere.dev/assets/img/preview.png"
    - name: "twitter:card"
      content: "summary_large_image"
    - name: "og:type"
      content: "website"
    - name: "og:url"
      content: "https://status.gioco.lol"
    
  
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.gioco.lol
  # baseUrl: /your-repo-name
  logoUrl: https://giocoliere.dev/assets/img/logo.png
  name: Giocoliere | Status
  introTitle: "**This** is my official Giocoliere status page, powered entirely by GitHub."
  introMessage: Here, you'll find comprehensive updates and detailed information regarding my services, alongside direct links to my ["wesbsite v0.7"](https://giocoliere.dev).
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
